# This file was generated by GoReleaser. DO NOT EDIT.
cask "darwinvpn" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ad7fa69f8c87228bbd0a4dd90162f7f78265b14f6adaf3d0430d50904412e3e8"
      url "https://github.com/mrsmsn/darwinvpn/releases/download/v#{version}/darwinvpn_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0a4a17e8fdf252df32ec9e9894aa35314ab114b2b564c6301a5c43c0ae0fdb4"
      url "https://github.com/mrsmsn/darwinvpn/releases/download/v#{version}/darwinvpn_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "darwinvpn"
  desc "macOS CLI for IKEv2 and Tunnel Provider VPNs via NetworkExtension"
  homepage "https://github.com/mrsmsn/darwinvpn"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "darwinvpn"

  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/darwinvpn"]
  end

  # No zap stanza required

end
